apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.5.1
  # image: debezium/connect:2.3  
  replicas: 1
  bootstrapServers: debezium-cluster-kafka-bootstrap:9092
  config:
    config.providers: secrets
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configuredin the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  build:
    output:
      type: docker
      image: 10.100.195.89/my-connect-cluster:latest
    plugins:
      # - name: kafka-connect-file
      #   artifacts:
      #     - type: maven
      #       group: org.apache.kafka
      #       artifact: connect-file
      #       version: 3.5.1
      - name: debezium-connector-sqlserver
        artifacts:
          - type: maven
            # repository: https://repo1.maven.org/maven2
            group: io.debezium
            artifact: debezium-connector-sqlserver
            version: 2.3.2.Final
          # - type: tgz
          #   url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-sqlserver/2.3.2.Final/debezium-connector-sqlserver-2.3.2.Final-plugin.tar.gz